# Workflow name
name: 'Chromatic'

on: push

jobs:
    chromatic-deployment:
        # Operating System
        runs-on: ubuntu-latest
        # Job steps
        steps:
            - uses: actions/checkout@v1
            - name: Install dependencies
              run: npm install
            - name: Publish to Chromatic
              uses: chromaui/action@v1
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
