name: Deploy to AWS SSM Parameter Store

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: github-actions-SSM-deploy
      - name: Combine and Upload JSON to AWS SSM
        run: |
          bash ./scripts/combine-json.sh
